### ISSUE TITLE
Remove google analytics code

### ISSUE THREAD

**Issue by mtpatter** [sthapa15/sthapa15.github.io#1]
https://github.com/sthapa15/sthapa15.github.io/blob/e32df8203ca0c05822daba567e08a448a56d62d2/_includes/footer.html#L7

Hi there, you seem to be using my google analytics code on your website - probably from using my github repo as your template.  Can you please remove this?

**Comment by sthapa15** [comment]
I've removed it. Apologies!

**Comment by mtpatter** [comment]
No worries, thanks!
